import {Inter,Outfit} from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Trackify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={inter.className}
        >
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
